name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        env:
          DJANGO_DEBUG: "1"
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run
          python manage.py collectstatic --noinput
